# Developed by Eng Mouaz M AlShahmeh
name: duck_hunt_flutter_game
description: Developed by Eng Mouaz M AlShahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  audioplayers: ^1.1.1
  flutter_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dog/double/
    - assets/images/dog/find/
    - assets/images/dog/jump/
    - assets/images/dog/laugh/
    - assets/images/dog/single/
    - assets/images/dog/sniff/
    - assets/images/duck/black/dead/
    - assets/images/duck/black/left/
    - assets/images/duck/black/right/
    - assets/images/duck/black/shot/
    - assets/images/duck/black/top-left/
    - assets/images/duck/black/top-right/
    - assets/images/duck/red/dead/
    - assets/images/duck/red/left/
    - assets/images/duck/red/right/
    - assets/images/duck/red/shot/
    - assets/images/duck/red/top-left/
    - assets/images/duck/red/top-right/
    - assets/images/hud/bullet/
    - assets/images/hud/score-dead/
    - assets/images/hud/score-live/
    - assets/images/scene/back/
    - assets/images/scene/tree/
    - assets/sounds/
